#!/bin/sh

# DESCRIPTION:
# * make and save a screenshot
# * [optionally] copy to clipboard
# * [optionally] optimize it
# * [optionally] OCR it
#
# ARGUMENTS:
# * mode: full|selected|focused
#
# ENVIRONMENT VARIABLES:
# * SCREENSHOT_DOCKER_HOST: set to prefer using docker for image optimization
#     Examples: `unix:///var/run/docker.sock` for local execution
#               `ssh://root@your.server.com` for remote
#
# DEPENDENCIES:
# * Interpreter: POSIX shell + coreutils
# * Screenshot tool:
#   * menyoki  + xdotool + (hacksaw | xrectsel | slop)
#   * shotgun  + xdotool + (hacksaw | xrectsel | slop)
#   * maim     + xdotool
#   * escrotum + xdotool
#   * mss      + xdotool + (hacksaw | xrectsel | slop)
#   * scrot
#   * (graphicsmagick | imagemagick) + xdotool
# * Clipboard tool [opt]: xclip | xsel
# * Image lossless optimizer [opt]: oxipng | ect | leanify | pngout | optipng | pngcrush | advpng | jpegoptim | jpegtran
# * OCR tool [opt]: tesseract + tesseract-ocr-rus | easyocr
# * Locks manager [opt]: flock
#


set -o errexit  # exit on fail
set -o nounset  # exit on undeclared variable
# set -o xtrace   # trace execution


save_dir=${SCREENSHOT_DIR:-${HOME}/screenshots}
save_ext=png
save_date=$(date '+%s_%Y.%m.%d_%H:%M:%S')
save_name=${save_date}.${save_ext}
save_path=${save_dir}/${save_name}


# We expect word splitting here
# shellcheck disable=2046
get_size() { set -- $(ls -dn "$1") && printf %s "$5"; }
has() { command -v "$@" >/dev/null; }
has_focus_window_getter() { has xdotool || has xprop sed; }
has_selection_getter() { has hacksaw || has xrectsel || has slop; }
was_optimized() { printf "%s\n" "${save_name}" >> "${save_dir}/.optimized"; }

get_focused_window() {
    if has xdotool; then
        xdotool getwindowfocus -f
    elif has xprop sed; then
        printf '%d\n' "$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)"
    else
        printf "Internal error!\n" >&2
        exit 1
    fi
}

usage() {
    printf "\
Usage: screenshot COMMAND
DESCRIPTION
    Make a screenshot.
COMMANDS:
full
        Make a full screen screenshot.
select
        Select a screenshot area with a mouse.
focused
        Make a screenshot of the currently focused window.
" >&2
}

check_user_input() {
    if [ $# -ne 1 ] || ! {
        [ "$1" = "full" ] ||
        [ "$1" = "select" ] ||
        [ "$1" = "focused" ];
    }
    then
        usage
        exit 1
    fi
}


# https://wiki.archlinux.org/title/Screen_capture#Dedicated_software
make_screenshot() {
    if has_selection_getter && has menyoki; then
        selection=$(
            if has hacksaw; then
                hacksaw
            elif has xrectsel; then
                xrectsel
            else
                slop
            fi
        )
        case $1 in
        'full'   ) menyoki -q capture --root                       png save -- "${save_path}" ;;
        'select' ) menyoki -q capture --root --size "${selection}" png save -- "${save_path}" ;;
        'focused') menyoki -q capture --focus                      png save -- "${save_path}" ;;
        esac

    elif has_focus_window_getter && has_selection_getter && has shotgun; then
        selection=$(
            if has hacksaw; then
                hacksaw  -f "--id %i --geometry %g"
            elif has xrectsel; then
                xrectsel -f "        --geometry %wx%h+%x+%y"
            else
                slop     -f "--id %i --geometry %g"
            fi
        )
        # shellcheck disable=SC2086
        case $1 in
        'full'   ) shotgun                              -- "${save_path}" ;;
        'select' ) shotgun ${selection}                 -- "${save_path}" ;;
        'focused') shotgun --id "$(get_focused_window)" -- "${save_path}" ;;
        esac

    elif has_focus_window_getter && has maim; then
        case $1 in
        'full'   ) maim                                  -- "${save_path}" ;;
        'select' ) maim --select                         -- "${save_path}" ;;
        'focused') maim --window "$(get_focused_window)" -- "${save_path}" ;;
        esac

    elif has_focus_window_getter && has escrotum; then
        case $1 in
        'full'   ) escrotum                               -- "${save_path}" ;;
        'select' ) escrotum --select                      -- "${save_path}" ;;
        'focused') escrotum --xid "$(get_focused_window)" -- "${save_path}" ;;
        esac

    elif has_focus_window_getter && has_selection_getter && has mss; then
        selection=$(
            if has hacksaw; then
                hacksaw  -f "%x,%y,%w,%h"
            elif has xrectsel; then
                xrectsel -f "%x,%y,%w,%h"
            else
                slop     -f "%x,%y,%w,%h"
            fi
        )
        case $1 in
        'full'   ) mss                                       --output "${save_path}" ;;
        'select' ) mss --coordinates "${selection}"          --output "${save_path}" ;;
        'focused') mss --coordinates "$(get_focused_window)" --output "${save_path}" ;;
        esac

    elif has scrot; then
        case $1 in
        'full'   ) scrot --multidisp -- "${save_path}" ;;
        'select' ) scrot --select    -- "${save_path}" ;;
        'focused') scrot --focused   -- "${save_path}" ;;
        esac

    elif has_focus_window_getter && has gm; then
        case $1 in
        'full'   ) gm import -window root                    "${save_path}" ;;
        'select' ) gm import                                 "${save_path}" ;;
        'focused') gm import -window "$(get_focused_window)" "${save_path}" ;;
        esac

    elif has_focus_window_getter && has import; then
        case $1 in
        'full'   ) import -window root                    -- "${save_path}" ;;
        'select' ) import                                 -- "${save_path}" ;;
        'focused') import -window "$(get_focused_window)" -- "${save_path}" ;;
        esac

    else
        # current xwd lacks -rect option on ubuntu: can't test
        # imlib2_grab can only make a fullscreen shot
        printf "No graphics/image-magick's import or scrot or escrotum or maim or shotgun or menyoki installed\n" >&2
        exit 1

    fi
}


copy_to_clipboard() {
    if has xclip; then
        printf %s "${save_path}" | xclip -in -selection primary
        xclip -selection clipboard -target image/png <"${save_path}"

    elif has xsel; then
        printf %s "${save_path}" | xsel --input --primary
        printf %s "${save_path}" | xsel --input --clipboard
    fi
}


# https://wiki.archlinux.org/title/List_of_applications/Multimedia#Console
optimize_image() {
    if [ -n "${SCREENSHOT_DOCKER_HOST:-}" ] && docker info >/dev/null 2>&1; then
        (
            export DOCKER_HOST=${SCREENSHOT_DOCKER_HOST}
            # Create a container that would auto-destroy in 10 minutes
            container_id=$(
                docker run --rm -d \
                    skhaz/compression-tools \
                    sleep $(( 60 * 10 ))
            )
            # Destroy container on exit from brackets
            trap 'docker rm -f "${container_id}" >/dev/null; trap - EXIT; exit' EXIT INT HUP
            # Copy file to container, process it, and copy back
            docker cp "${save_path}" "${container_id}:/${save_name}"
            docker exec -ti "${container_id}" ect -9 "/${save_name}"
            docker container cp "${container_id}:/${save_name}" "${save_path}"

            was_optimized
        )

    elif [ "${save_ext}" = "png" ] && has oxipng; then
        oxipng --quiet --opt max --threads 1 -- "${save_path}"
        was_optimized

    elif has etc; then
        ect -9 "${save_path}"
        was_optimized

    elif has leanify; then
        leanify --iteration 100 -- "${save_path}"
        was_optimized

    elif [ "${save_ext}" = "png" ] && has pngout; then
        pngout "${save_path}" "/tmp/${save_name}" || [ $? = 2 ]
        mv "/tmp/${save_name}" "${save_path}"
        was_optimized

    elif [ "${save_ext}" = "png" ] && has optipng; then
        optipng -o7 -strip all -- "${save_path}"
        was_optimized

    elif [ "${save_ext}" = "png" ] && has pngcrush; then
        pngcrush -brute -reduce "${save_path}" "/tmp/${save_name}"
        if [ "$(get_size "/tmp/${save_name}")" -lt "$(get_size "${save_path}")" ]; then
            mv "/tmp/${save_name}" "${save_path}"
        fi
        was_optimized

    elif [ "${save_ext}" = "png" ] && has advpng; then
        advpng --recompress --shrink-insane --iter=100 -- "${save_path}"
        was_optimized

    elif [ "${save_ext}" = "jpg" ] && has jpegoptim; then
        jpegoptim --strip-all -- "${save_path}"
        was_optimized

    elif [ "${save_ext}" = "jpg" ] && has jpegtran; then
        jpegtran -copy none -perfect -optimize -outfile "/tmp/${save_name}" "${save_path}"
        if [ "$(get_size "/tmp/${save_name}")" -lt "$(get_size "${save_path}")" ]; then
            mv "/tmp/${save_name}" "${save_path}"
        fi
        was_optimized

    fi
}


ocr_image() {
    if has tesseract; then
        tesseract -l eng+rus --psm 1 "${save_path}" "${save_dir}/${save_date}"
    elif has easyocr; then
        easyocr --lang en ru --detail 0 --file "${save_path}" > "${save_dir}/${save_date}.txt"
    fi
}


check_user_input "$@"

mkdir -p "${save_dir}"

make_screenshot "$@"

printf '%s\n' "${save_path}"

copy_to_clipboard

(
    # Execute under lock
    # if flock is available
    if has flock; then
        flock 9
    fi

    optimize_image >&2

    ocr_image >&2

) 9>"/var/lock/screenshot-$(id -u).lock"
